# Generated by Django 4.2.7 on 2025-01-08 18:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_news_descripcion_gramatica_news_palabras_a_buscar_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="audio",
            field=models.FileField(blank=True, null=True, upload_to="news/audio/"),
        ),
    ]
