# Generated by Django 4.2.7 on 2025-01-25 21:40

import cloudinary_storage.storage
import cloudinary_storage.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_news_image_news_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='audio',
            field=models.ImageField(blank=True, null=True, storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage(), upload_to='videos/', validators=[cloudinary_storage.validators.validate_video]),
        ),
    ]
