# Generated by Django 4.2.7 on 2025-01-07 16:24

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("content", models.TextField()),
                ("author", models.CharField(max_length=100)),
                ("published_date", models.DateTimeField()),
                ("tags", models.CharField(blank=True, max_length=255)),
                ("image", models.ImageField(upload_to="news/")),
            ],
        ),
    ]
