# Generated by Django 4.2.7 on 2023-11-30 03:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='category',
            field=models.ForeignKey(choices=[('politics', 'Política'), ('sports', 'Deportes'), ('tech', 'Tecnología')], on_delete=django.db.models.deletion.CASCADE, to='api.category'),
        ),
    ]
